/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AppointmentStatusEnum = 0 | 1 | 2 | 3;

export const AppointmentStatusEnum = {
    NUMBER_0: 0 as AppointmentStatusEnum,
    NUMBER_1: 1 as AppointmentStatusEnum,
    NUMBER_2: 2 as AppointmentStatusEnum,
    NUMBER_3: 3 as AppointmentStatusEnum
};

