/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRole = 1 | 2 | 3 | 4;

export const UserRole = {
    NUMBER_1: 1 as UserRole,
    NUMBER_2: 2 as UserRole,
    NUMBER_3: 3 as UserRole,
    NUMBER_4: 4 as UserRole
};

