/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUpdateDto { 
    userId?: number;
    userName?: string | null;
    role?: string | null;
    email?: string | null;
    password?: string | null;
}

