/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './userRole';


export interface User { 
    createdBy?: number;
    createdAt?: Date;
    updatedBy?: number;
    updatedAt?: Date | null;
    userID?: number;
    email: string;
    userName?: string | null;
    role?: UserRole;
    refreshToken?: string | null;
    tokenCreated?: Date;
    tokenExpires?: Date;
}
export namespace User {
}


