/**
 * HealthCenter
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Practitioner { 
    createdAt?: Date;
    updatedAt?: Date;
    createdBy?: number;
    createdDate?: Date;
    lastModifiedBy?: number;
    lastModifiedDate?: Date | null;
    practitionerId?: number;
    firstName: string;
    lastName: string;
    specialty?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
}

