export * from './appointments.service';
import { AppointmentsService } from './appointments.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './imageRecords.service';
import { ImageRecordsService } from './imageRecords.service';
export * from './inpatients.service';
import { InpatientsService } from './inpatients.service';
export * from './labTests.service';
import { LabTestsService } from './labTests.service';
export * from './medications.service';
import { MedicationsService } from './medications.service';
export * from './patients.service';
import { PatientsService } from './patients.service';
export * from './practitionerAvailabilities.service';
import { PractitionerAvailabilitiesService } from './practitionerAvailabilities.service';
export * from './practitionerSchedules.service';
import { PractitionerSchedulesService } from './practitionerSchedules.service';
export * from './practitioners.service';
import { PractitionersService } from './practitioners.service';
export * from './prescriptions.service';
import { PrescriptionsService } from './prescriptions.service';
export * from './signatures.service';
import { SignaturesService } from './signatures.service';
export * from './sse.service';
import { SseService } from './sse.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './weatherForecast.service';
import { WeatherForecastService } from './weatherForecast.service';
export const APIS = [AppointmentsService, AuthService, ImageRecordsService, InpatientsService, LabTestsService, MedicationsService, PatientsService, PractitionerAvailabilitiesService, PractitionerSchedulesService, PractitionersService, PrescriptionsService, SignaturesService, SseService, UsersService, WeatherForecastService];
